version: '3.8'

services:
  react-app:
    build: .
    container_name: bulkbuddy
    image:bulkbuddy: 01
    ports:
      - "5173:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
