apiVersion: v1
kind: Service
metadata:
  name: bulkbuddy-service
spec:
  type: NodePort
  selector:
    app: bulkbuddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
